#define AEM_API_GETADMINDATA 51
#define AEM_API_GETUSERINFO 50
#define AEM_LEN_ACCESSKEY crypto_box_SECRETKEYBYTES
#define AEM_LEN_KEY_ACC crypto_box_SECRETKEYBYTES
#define AEM_LEN_KEY_ADR crypto_pwhash_SALTBYTES
#define AEM_LEN_KEY_API crypto_box_SECRETKEYBYTES
#define AEM_LEN_KEY_MASTER crypto_secretbox_KEYBYTES
#define AEM_LEN_KEY_MNG crypto_secretbox_KEYBYTES
#define AEM_LEN_KEY_STO 32
#define AEM_LEN_PERSONAL (4096 - 13)
#define AEM_MAXLEN_DOMAIN 32
#define AEM_MAXLEN_HOST 32
#define AEM_PORT_HTTPS 443
#define AEM_PORT_MANAGER 940
#define AEM_USERLEVEL_MAX 3
#define AEM_USERLEVEL_MIN 0
