#define AEM_MOUNTDIR_OPTS "uid=0,gid=0,mode=1000,size=1"
#define AEM_MOUNTDIR_FLAGS (MS_NOSUID | MS_NOATIME | MS_SILENT)
#define AEM_MOUNTDIR "/var/lib/allears/mounts"

#define AEM_PROCESSTYPE_MTA 0
#define AEM_PROCESSTYPE_WEB 1
#define AEM_PROCESSTYPE_API 2
#define AEM_PROCESSTYPE_ACCOUNT 10
#define AEM_PROCESSTYPE_STORAGE 11
#define AEM_PROCESSTYPE_ENQUIRY 12
