#define AEM_CHROOT "/tmp/allears"

#define AEM_PROCESSTYPE_MTA 0
#define AEM_PROCESSTYPE_WEB 1
#define AEM_PROCESSTYPE_API 2
#define AEM_PROCESSTYPE_ACCOUNT 10
#define AEM_PROCESSTYPE_STORAGE 11
#define AEM_PROCESSTYPE_ENQUIRY 12
