#define AEM_TLS_CIPHERSUITES_HIGH \
	MBEDTLS_TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,\
	MBEDTLS_TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,\
	MBEDTLS_TLS_ECDHE_ECDSA_WITH_AES_256_CCM,\
	MBEDTLS_TLS_ECDHE_ECDSA_WITH_AES_256_CCM_8,\
	MBEDTLS_TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,\
	MBEDTLS_TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,\
	MBEDTLS_TLS_ECDHE_ECDSA_WITH_AES_128_CCM,\
	MBEDTLS_TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8,\
	MBEDTLS_TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,\
	MBEDTLS_TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,\
	0

#define AEM_TLS_CURVES_HIGH \
	MBEDTLS_ECP_DP_CURVE448,\
	MBEDTLS_ECP_DP_CURVE25519,\
	MBEDTLS_ECP_DP_SECP521R1,\
	MBEDTLS_ECP_DP_SECP384R1,\
	MBEDTLS_ECP_DP_NONE

#define AEM_TLS_HASHES_HIGH \
	MBEDTLS_SSL_HASH_SHA512,\
	MBEDTLS_MD_NONE
