#ifndef AEM_INTCOM_COMMON_H
#define AEM_INTCOM_COMMON_H

#define UINT24_MAX 16777215UL

typedef enum {
	AEM_INTCOM_TYPE_ACCOUNT,
	AEM_INTCOM_TYPE_ENQUIRY,
	AEM_INTCOM_TYPE_STORAGE,
	AEM_INTCOM_TYPE_NULL
} aem_intcom_type_t;

#endif
