#ifndef AEM_API_ERROR_H
#define AEM_API_ERROR_H

// Server-side error code range: 0x21-0xFF (33-255)

// 0x21-0x2F	Generic
#define AEM_API_ERR_FORMAT    0x21
#define AEM_API_ERR_ADMINONLY 0x22
#define AEM_API_ERR_MISC      0x23
#define AEM_API_ERR_INTERNAL  0x24
#define AEM_API_ERR_TODO      0x25
#define AEM_API_ERR_FIXME     0x26

#define AEM_API_ERR_NOTEXIST  0x2A
#define AEM_API_ERR_EXIST     0x2B

// 0xE0-0xEF	Message/Create
#define AEM_API_ERR_MESSAGE_CREATE_EXT_MINLEVEL        0xE0
#define AEM_API_ERR_MESSAGE_CREATE_EXT_FORMAT_FROM     0xE1
#define AEM_API_ERR_MESSAGE_CREATE_EXT_FORMAT_TO       0xE2
#define AEM_API_ERR_MESSAGE_CREATE_EXT_FORMAT_REPLYID  0xE3
#define AEM_API_ERR_MESSAGE_CREATE_EXT_FORMAT_SUBJECT  0xE4
#define AEM_API_ERR_MESSAGE_CREATE_EXT_INVALID_REPLYID 0xE5
#define AEM_API_ERR_MESSAGE_CREATE_EXT_INVALID_FROM    0xE6
#define AEM_API_ERR_MESSAGE_CREATE_EXT_INVALID_TO      0xE7
#define AEM_API_ERR_MESSAGE_CREATE_EXT_BODY_SIZE       0xE8
#define AEM_API_ERR_MESSAGE_CREATE_EXT_BODY_UTF8       0xE9
#define AEM_API_ERR_MESSAGE_CREATE_EXT_BODY_CONTROL    0xEA
#define AEM_API_ERR_MESSAGE_CREATE_EXT_LINE_TOOLONG    0xEB
#define AEM_API_ERR_MESSAGE_CREATE_EXT_BODY_FORMAT     0xEC
#define AEM_API_ERR_MESSAGE_CREATE_EXT_BODY_TOOSHORT   0xED
#define AEM_API_ERR_MESSAGE_CREATE_EXT_TODOMAIN        0xEE
// 0xEF unused

// 0xF0-0xF9	Message/Create sendMail()
#define AEM_API_ERR_MESSAGE_CREATE_SENDMAIL_GREET 0xF0
#define AEM_API_ERR_MESSAGE_CREATE_SENDMAIL_EHLO  0xF1
#define AEM_API_ERR_MESSAGE_CREATE_SENDMAIL_STLS  0xF2
#define AEM_API_ERR_MESSAGE_CREATE_SENDMAIL_SHAKE 0xF3
#define AEM_API_ERR_MESSAGE_CREATE_SENDMAIL_NOTLS 0xF4
#define AEM_API_ERR_MESSAGE_CREATE_SENDMAIL_MAIL  0xF5
#define AEM_API_ERR_MESSAGE_CREATE_SENDMAIL_RCPT  0xF6
#define AEM_API_ERR_MESSAGE_CREATE_SENDMAIL_DATA  0xF7
#define AEM_API_ERR_MESSAGE_CREATE_SENDMAIL_BODY  0xF8
// 0xF9 unused

// 0xFA-0xFF	Message/Create Int
#define AEM_API_ERR_MESSAGE_CREATE_INT_TOOSHORT     0xFA
#define AEM_API_ERR_MESSAGE_CREATE_INT_TS_INVALID   0xFB
#define AEM_API_ERR_MESSAGE_CREATE_INT_SUBJECT_SIZE 0xFC
#define AEM_API_ERR_MESSAGE_CREATE_INT_ADDR_NOTOWN  0xFD
#define AEM_API_ERR_MESSAGE_CREATE_INT_TO_NOTACCEPT 0xFE
#define AEM_API_ERR_MESSAGE_CREATE_INT_TO_SELF      0xFF

#endif
